Added jurisprudencia-rss files
stjiris/jurisprudencia-rss pull request #1
Opened 2024-05-05 11:51 UTC by SobriKeN

2024-05-05 12:42 UTC, diogoalmiro requested changes

2024-05-05 12:42 UTC, diogoalmiro commented on src/index.ts
> +        if(counter >= 1000){
Should be an env var (e.g. RSS_MAX_FEED_SIZE)

2024-05-05 13:30 UTC, SobriKeN commented
Changes done, also created the environment variables in nextjs-jurisprudencia

2024-05-05 14:10 UTC, SobriKeN commented
RSS_MAX_FEED_SIZE is working

2024-05-06 00:33 UTC, diogoalmiro requested changes

2024-05-06 00:33 UTC, diogoalmiro commented on src/index.ts
> +        if(counter >= parseInt(process.env.RSS_MAX_FEED_SIZE!)){
As discussed in chat please review this logic. We should maybe do `if( feeds.get(...).items.length <= RSS_MAX_...SIZE ) feeds.get(...).addItem` before each addItem (specific or geral). No need to break from this for loop ever.

2024-05-06 18:31 UTC, SobriKeN commented
added the process limit logic for each rss

2024-05-06 19:47 UTC, diogoalmiro commented on src/index.ts
> +    for (let feedArea of map.keys()) {
<img width="186" alt="image" src="https://github.com/stjiris/jurisprudencia-rss/assets/13120173/baba1893-b82f-4c86-9694-2fb3a59376ba">
Unnecessary loop. (And unnecessary function) When we call `isAreaInFeed(....)` we could do `feeds.has(...)`

2024-05-06 19:48 UTC, diogoalmiro commented on src/index.ts
> +            continue;
use `if( feeds.get(...).items.length < parseInt(...) )` instead of if continue else

2024-05-06 19:52 UTC, diogoalmiro commented on src/index.ts
> +    feeds.forEach(async (feed,area) => {
I think for sake of promises this would be cleaner
```typescript
for( const [area, feed] of feeds.entries() ){
   ...
   await ...
}
```

2024-05-06 20:09 UTC, SobriKeN commented
all the details have been resolved

2024-05-07 09:48 UTC, diogoalmiro approved these changes

2024-05-07 09:49 UTC, merged